<?php

namespace Database\Seeders;

use App\Enums\DayOfWeek;
use App\Models\MataKuliah;
use Illuminate\Database\Seeder;

class MataKuliahSeeder extends Seeder
{
    public function run(): void
    {
        $mataKuliah = [
            [
                'kode' => 'IF301',
                'nama' => 'Algoritma dan Struktur Data',
                'sks' => 3,
                'kelas' => 'A',
                'dosen' => 'Dr. Andi Kurniawan, M.Kom',
                'ruangan' => 'Lab Komputer 1',
                'hari' => DayOfWeek::MONDAY->value,
                'jam_mulai' => '08:00',
                'jam_selesai' => '10:30',
                'lms' => 'Google Classroom',
                'lms_link' => 'https://classroom.google.com/c/if301-a',
                'semester' => 4,
                'tahun_ajaran' => 2026,
                'warna' => 'biru',
                'catatan' => 'Fokus pada latihan problem solving mingguan.',
                'is_active' => true,
            ],
            [
                'kode' => 'SI302',
                'nama' => 'Basis Data',
                'sks' => 3,
                'kelas' => 'B',
                'dosen' => 'Nur Aisyah, S.Kom., M.Cs',
                'ruangan' => 'Ruang 2.04',
                'hari' => DayOfWeek::TUESDAY->value,
                'jam_mulai' => '09:30',
                'jam_selesai' => '12:00',
                'lms' => 'Moodle',
                'lms_link' => 'https://lms.kampus.test/mk/si302-b',
                'semester' => 4,
                'tahun_ajaran' => 2026,
                'warna' => 'emerald',
                'catatan' => 'Praktikum menggunakan dataset akademik.',
                'is_active' => true,
            ],
            [
                'kode' => 'IF303',
                'nama' => 'Pemrograman Web Laravel',
                'sks' => 3,
                'kelas' => 'A',
                'dosen' => 'Muhammad Faisal, M.T',
                'ruangan' => 'Lab Web',
                'hari' => DayOfWeek::WEDNESDAY->value,
                'jam_mulai' => '13:00',
                'jam_selesai' => '15:30',
                'lms' => 'Google Classroom',
                'lms_link' => 'https://classroom.google.com/c/if303-a',
                'semester' => 4,
                'tahun_ajaran' => 2026,
                'warna' => 'sky',
                'catatan' => 'Setiap pekan ada mini project dan review kode.',
                'is_active' => true,
            ],
            [
                'kode' => 'IF304',
                'nama' => 'Rekayasa Perangkat Lunak',
                'sks' => 3,
                'kelas' => 'A',
                'dosen' => 'Rina Marlina, M.Kom',
                'ruangan' => 'Ruang 3.02',
                'hari' => DayOfWeek::THURSDAY->value,
                'jam_mulai' => '10:00',
                'jam_selesai' => '12:30',
                'lms' => 'Moodle',
                'lms_link' => 'https://lms.kampus.test/mk/if304-a',
                'semester' => 4,
                'tahun_ajaran' => 2026,
                'warna' => 'amber',
                'catatan' => 'Dokumen analisis dan sprint board wajib diperbarui.',
                'is_active' => true,
            ],
            [
                'kode' => 'IF305',
                'nama' => 'Interaksi Manusia dan Komputer',
                'sks' => 2,
                'kelas' => 'B',
                'dosen' => 'Dewi Lestari, S.Sn., M.Ds',
                'ruangan' => 'Studio UI/UX',
                'hari' => DayOfWeek::FRIDAY->value,
                'jam_mulai' => '08:30',
                'jam_selesai' => '10:10',
                'lms' => 'Google Classroom',
                'lms_link' => 'https://classroom.google.com/c/if305-b',
                'semester' => 4,
                'tahun_ajaran' => 2026,
                'warna' => 'rose',
                'catatan' => 'Setiap tugas harus menyertakan catatan usability.',
                'is_active' => true,
            ],
            [
                'kode' => 'SI306',
                'nama' => 'Analisis dan Perancangan Sistem',
                'sks' => 3,
                'kelas' => 'A',
                'dosen' => 'Hendra Wijaya, M.Kom',
                'ruangan' => 'Ruang 2.07',
                'hari' => DayOfWeek::SATURDAY->value,
                'jam_mulai' => '09:00',
                'jam_selesai' => '11:30',
                'lms' => 'Moodle',
                'lms_link' => 'https://lms.kampus.test/mk/si306-a',
                'semester' => 4,
                'tahun_ajaran' => 2026,
                'warna' => 'slate',
                'catatan' => 'Case study diambil dari sistem akademik kampus.',
                'is_active' => true,
            ],
            [
                'kode' => 'IF307',
                'nama' => 'Jaringan Komputer',
                'sks' => 3,
                'kelas' => 'A',
                'dosen' => 'Yusuf Hamzah, S.T., M.T',
                'ruangan' => 'Lab Jaringan',
                'hari' => DayOfWeek::MONDAY->value,
                'jam_mulai' => '13:30',
                'jam_selesai' => '16:00',
                'lms' => 'Moodle',
                'lms_link' => 'https://lms.kampus.test/mk/if307-a',
                'semester' => 4,
                'tahun_ajaran' => 2026,
                'warna' => 'cyan',
                'catatan' => 'Praktikum simulasi dilakukan bergiliran per kelompok.',
                'is_active' => true,
            ],
            [
                'kode' => 'KU101',
                'nama' => 'Bahasa Inggris Akademik',
                'sks' => 2,
                'kelas' => 'C',
                'dosen' => 'Anita Sari, M.Hum',
                'ruangan' => 'Ruang Bahasa',
                'hari' => DayOfWeek::THURSDAY->value,
                'jam_mulai' => '15:45',
                'jam_selesai' => '17:15',
                'lms' => 'Google Classroom',
                'lms_link' => 'https://classroom.google.com/c/ku101-c',
                'semester' => 4,
                'tahun_ajaran' => 2026,
                'warna' => 'violet',
                'catatan' => 'Materi fokus pada reading journal dan presentation practice.',
                'is_active' => false,
            ],
        ];

        foreach ($mataKuliah as $item) {
            MataKuliah::updateOrCreate(
                [
                    'kode' => $item['kode'],
                    'kelas' => $item['kelas'],
                ],
                $item
            );
        }
    }
}
